// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhmekdcmrykzmevgjoau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobWVrZGNtcnlrem1ldmdqb2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTUxNzYsImV4cCI6MjA3MTc5MTE3Nn0.xs8Apw7GmWqJgRPKTS8eJm0M15nna-hPnyDu5nJdKKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});